cursor move between screens
zigen-project/zen pull request #101
Opened 2022-08-06 05:33 UTC by watasuke102

## Context

implement a part of #89 

## Summary

The cursor is moved within the screen, and jump to other screens.

## How to check behavior

1. start zen
2. try to move out of screen - it cannot
3. try to move adjacent screen - the cursor is moved to that screen

2022-08-06 14:09 UTC, Aki-7 requested changes

2022-08-06 14:09 UTC, Aki-7 commented on zen/scene/screen.c
> +  self->box.height = output->wlr_output->height;
And please use `wlr_output_effective_resolution`

2022-08-14 12:37 UTC, watasuke102 commented on zen/cursor.c
> +zn_cursor_move(struct zn_cursor* self, int x, int y)
> Isn't zn_cursor_move_relative enough?
No. This is used by `zn_cursor_move_center()`.

2022-08-14 12:45 UTC, watasuke102 commented on zen/cursor.c
> +zn_cursor_move(struct zn_cursor* self, int x, int y)
I think naming `zn_cursor_process_move()` looks good.

2022-08-14 14:14 UTC, Aki-7 approved these changes
Thank you!

2022-08-14 14:15 UTC, merged