Send pointer event
zigen-project/zen pull request #105
Opened 2022-08-14 14:23 UTC by watasuke102

## Context

implement a part of #89 

## Summary

Give position information to each views, and send enter/leave/motion/axis event from pointer when the cursor is moved on view.

## How to check behavior

1. start zen with -s option
  - `weston-clickdot` is recommended for testing `motion` event
  - `weston-cliptest` is recommended for testing `axis` event
3. move the cursor or scroll on view
4. events are sended

2022-08-15 02:38 UTC, Aki-7 requested changes

2022-08-15 02:38 UTC, Aki-7 commented on zen/scene/screen.c
> +}
This code is good, but could you please render the views in reverse order (in render-2d.c, zn_render_2d_screen)?
I think screen->views are ordered from from to bottom.
We need to render views from bottom to top.

I know it's a bug made before this PR, but please.

2022-08-15 02:38 UTC, Aki-7 commented on include/zen/scene/view.h
> +  int x, y;
```suggestion
  double x, y;
```

2022-08-15 02:38 UTC, Aki-7 commented on zen/scene/view.c
> +
1. Rather than createing zn_xdg_toplevel_view_focus and zn_xwayland_view_focus, it's better to add new function pointer member to zn_view_impl, by which we can make xdg_toplevel and xwayland views more uniform.
2. Most logic regarding views should be described in view.c rather than xdg-toplevel-view.c or xwayland-view.c, and only view type (xdg or xwayland) dependent processes should be delegated to them through zn_view_impl interface. That is, the name of zn_xwayland_view_set_activated is better than zn_xwayland_view_focus.
3. Would you explain what is wlr_xdg_toplevel_set_activate, wlr_xwayland_surface_activate and wlr_xwayland_surface_stack? Are those necessary now?

2022-08-15 02:38 UTC, Aki-7 commented on zen/xdg-toplevel-view.c
> +  zn_xdg_toplevel_view_focus(self);
I think views should be focused every time it's mapped, so it's better to focus a view in zn_view_map_to_screen.

2022-08-15 02:38 UTC, Aki-7 commented on zen/xdg-toplevel-view.c
> +  zn_xdg_toplevel_view_focus(self);
And there is no corresponding code in xwayland-view.c

2022-08-15 05:14 UTC, watasuke102 commented on zen/scene/view.c
> +
`wlr_(xwayland|xdg_toplevel)_set_activate()` is core of this `focus` process. `wlr_xwayland_surface_restack()` is called here because sway called this at simillar function. But in fact, I don't know how behave this because sending event to xwayland client doesn't work well yet, so I will remove this.

These `focus` process doesn't required in terms of behavior, but only make it easier to visually see which view is focusing. I can remove these process too, but are these **really** unnecessary?

2022-08-15 06:02 UTC, Aki-7 commented on zen/scene/view.c
> +
> wlr_(xwayland|xdg_toplevel)_set_activate() is core of this focus process.

What are these functions doing?

> sending event to xwayland client doesn't work well yet.

What do you mean? What events? Leaving those event not working doesn't make problems?

> These focus process doesn't required in terms of behavior, but only make it easier to visually see which view is focusing.

Does 'visually' mean the code is visually understandable for programmers?

2022-08-15 07:03 UTC, watasuke102 commented on zen/scene/view.c
> +
> What are these functions doing?

Sorry for these remark because I'm lack of complehension, but May I ask what are you intending?

> What events?

It is pointer events such as motion.

> Leaving those event not working doesn't make problems?

No, so I will deal this problem later (in this PR).

> Does 'visually' mean the code is visually understandable for programmers?

No, it means, focused view's border (including the top of the view, usually contains title text and minimize/maximize/close button) is shown more brightly than not focused view's border (try to add `return;` line to the first line of `zn_xdg_toplevel_view_focus()`). As I mentioned before comment, these `focus` process doesn't required (in terms of behavior).

2022-08-15 07:12 UTC, watasuke102 commented on zen/scene/screen.c
> +}
Is following code resolves this? (441bc46)

```diff
- wl_list_for_each(view, &self->views, link)
+ wl_list_for_each_reverse(view, &self->views, link)
```

2022-08-15 07:27 UTC, Aki-7 commented on zen/scene/view.c
> +
> Sorry for these remark because I'm lack of complehension, but May I ask what are you intending?

It's just a question. I want to know what the `set_activated` means. Sending set_activated event to clients? Moving the view forward? (I think neither of them). I want to know what `set_activated` functions do, and also I want you to know it.

> No, it means, ...

Do you mean that kind of visual cue for focusing view has already been realized in the current code (https://github.com/zigen-project/zen/pull/105/commits/84f1de52b927df52532d6110fdd8ca956bdeb3c5)?

I couldn't confirm that a view's frame got more bright when the view is focused.

2022-08-15 07:32 UTC, Aki-7 commented on zen/scene/screen.c
> +}
I don't think so. 441bc46 assumes screen::views has views from back to front. It's ok, but then a view should be inserted at the last of screen::views when created.

2022-08-15 09:20 UTC, watasuke102 commented on zen/scene/view.c
> +
> I would like you to find it out.

Needless to say I implemented this because I think it is necessary, but I also understand that it may be my prefer rather than wide perspective, so I requested review.

You asked at first to me, `Are those necessary now?`, I interpreted this as you think it is not necessary now by some reasons, but I couldn't guess the reasons. May I ask about its reason?

> Sending set_activated event to clients? Moving the view forward? (I think neither of them)

Ok, it really helpful because I didn't know how much detail to describe.

`wlr_xdg_toplevel_set_activated(wlr_xdg_surface* surface, bool activated)` is set `activated` to `surface->scheduled.activated`, and add surface configurating event (`surface_send_configure()`) to event loop.  
On configurating, if the surface is xdg_toplevel and `surface->scheduled.activated` is true, add activated status to xdg_toplevel's state.

I'm doesn't x11 well, so I couldn't understand  `wlr_xwayland_surface_activate(wlr_xwayland_surface *xsurface, bool activated)`, but I found that this function finally call `xcb_change_property()`. It looks updating active window... (understanding `xcb_atom_t` is might helpful, if required more understanding, I learn about this)

> I couldn't confirm that a view's frame got more bright when the view is focused

Sorry, on the current code, I forget to unfocus view (that's why I said that "add `return;` to..."), so differences are not shown.

2022-08-15 11:29 UTC, Aki-7 commented on zen/scene/view.c
> +
> You asked at first to me, Are those necessary now?, I interpreted this as you think it is not necessary now by some reasons, but I couldn't guess the reasons. May I ask about its reason?

No, it was basically just a question but I was also thinking that if there was no positive answer it would be unnecessary.

Now you mean the current `zn_view_focus` func sends [xdg_toplevel::configure](https://wayland.app/protocols/xdg-shell#xdg_toplevel:event:configure) events to clients with active state included in its `states` arg, and then clients update window theme (frame, etc.) to be shown as active. That's the reason you implement `zn_(xdg_toplevel|xwayland)_view_focus`, right?

I didn't understand the meaning of `states` argument of xdg_toplevel::configure events, so this explanation is helpful for me. Thanks!

As you mentioned, if you include view activation feature in this PR, I want you to also implement deactivating feature.

2022-08-15 13:18 UTC, watasuke102 commented on zen/scene/view.c
> +
> That's the reason you implement zn_(xdg_toplevel|xwayland)_view_focus

That's right. 

Now, I think implementing `unfocus` process is little difficult, and `focus` process can be better by using `impl` (suggested at first). So I will remove `focus` process by this PR, and create another PR a while leter.

2022-08-16 03:05 UTC, Aki-7 requested changes

2022-08-16 03:05 UTC, Aki-7 commented on zen/pointer.c
> +    view_y = cursor->y - view->y;
Like sway, view_(x|y) should be calculated by zn_screen_get_view_at. The reason is that obtaining view_(x|y) is the responsibility of the scene side, such as view and screen, and should not be calculated in functions that handle pointer motion.

2022-08-16 05:00 UTC, Aki-7 commented on zen/scene/view.c
> +  wl_list_insert(screen->views.prev, &self->link);
Sorry for additional review. Please add comment to zn_screen::views.

"List of mapped zn_view in z-order, from bottom to top"

2022-08-16 05:01 UTC, watasuke102 commented on zen/scene/screen.c
> +    if (wlr_box_contains_point(&box, x, y)) {
because `wlr_box_contains_point()` requires wlr_box, not wlr_fbox.

2022-08-16 05:03 UTC, Aki-7 commented on zen/scene/screen.c
> +    if (wlr_box_contains_point(&box, x, y)) {
I see no reason why `wlr_box_contains_point` should be used.

2022-08-16 05:09 UTC, Aki-7 commented on zen/scene/screen.c
> +    if (wlr_box_contains_point(&box, x, y)) {
We are using screen world described in double precision floating point. Containment checks should also be performed with double precision floating point.

2022-08-16 06:56 UTC, Aki-7 commented on zen/scene/view.c
> +  wl_list_insert(screen->views.prev, &self->link);
I wanted to add a comment to the definition of screen struct, views member in screen.h. Sorry for the misunderstanding.

2022-08-16 06:58 UTC, Aki-7 commented
new comment: https://github.com/zigen-project/zen/pull/105#discussion_r946399592

You will fix xwayland problem in this PR, right?

2022-08-16 06:59 UTC, watasuke102 commented
Yes, I'm working about it.

2022-08-17 02:54 UTC, Aki-7 approved these changes
LGTM!

Great progress!!!

2022-08-17 02:55 UTC, merged