Set cursor surface
zigen-project/zen pull request #107
Opened 2022-08-17 02:57 UTC by watasuke102

## Context

In other DE, the cursor's appearance is changed when move cursor on view such as resize cursor. But zen can't.

## Summary

Listening wlr_seat's `request_set_cursor` event.

## How to check behavior

1. start zen with -s option (`weston-dnd` is recommended)
2. move the cursor to corners of view or object in view
3. cursor's appearance will be changed

2022-08-17 03:05 UTC, Aki-7 commented
I'll look into it now.

First, I want to ask you some current behavior.

- Will you correct cursor hotspot later? If so, it's ok.
- The cursor will not change in xwayland app, is this what you exepcted? I guess we should implement both in the same PR.

2022-08-17 03:07 UTC, watasuke102 commented
1. fix hotspot issue (#100) is already fixed, but it will be other PR.
2. I forgot to fix

2022-08-17 03:08 UTC, Aki-7 commented
> I forgot to fix

ok, let me know when fixed. I'll look into this then.

2022-08-18 06:11 UTC, Aki-7 requested changes
I found a bug, but you can leave it as an new issue.

Place cursor on the X client, and kill the X client
  - expected: cursor image will get back to the default one.
  - actual: unexpected cursor image are shown until moving the cursor.

2022-08-18 06:11 UTC, Aki-7 commented on zen/seat.c
> +}
Please check that the `self->wlr_seat->pointer_state.focused_client` is the same as `event->seat_client->client`.

See also https://github.com/swaywm/sway/blob/5543acff06981639086bc9a0fc9b608796a23e84/sway/input/cursor.c#L899-L924

2022-08-18 06:11 UTC, Aki-7 commented on zen/output.c
> +  }
Which surface is visible and needed to receive frame event are not simple. Those surfaces should be determined by zn_screen not zn_output. So Having a `zn_screen_for_each_visible_surface(iterfation_handler)` would be better.
But you don't have to do this in this PR.

2022-08-18 07:31 UTC, Aki-7 commented
Regarding [this](https://github.com/zigen-project/zen/pull/107#pullrequestreview-1076706795), please leave issue, and link to this PR.

2022-08-18 07:45 UTC, watasuke102 commented on zen/output.c
> +  }
I want to solve in this PR, but I can't complehend how to implement that. What is `iteration_handler`? What should it be checked?

2022-08-18 07:54 UTC, Aki-7 commented on zen/output.c
> +  }
Pseudo code
```c
typedef void (*zn_screen_surface_iterator_func_t) (struct zn_screen* screen, struct wlr_surface *surface, void *data);

void zn_screen_for_each_visible_surface(struct cn_screen *self, zn_screen_surface_iterator_func_t iterator, void *data) {
  for(view, self->view_list) {
    iterator(self, view->wlr_surface, data);
  }

  if (cursor->screen == self) iterator(self, view->wlr_surface, data);
} 
```

2022-08-19 13:51 UTC, Aki-7 commented on zen/render-2d.c
> +  if (cursor->texture) {
nits
```suggestion
  if (texture) {
```

2022-08-19 15:42 UTC, Aki-7 commented on zen/cursor.c
> +  self->surface = NULL;
```suggestion
  zn_cursor_set_surface(self, NULL);
```

2022-08-20 05:36 UTC, Aki-7 reviewed
https://github.com/zigen-project/zen/pull/107#discussion_r950276174

Do you forget this?

2022-08-20 05:36 UTC, Aki-7 commented on zen/cursor.c
> +  wl_list_remove(&self->destroy_surface_listener.link);
```suggestion
```

2022-08-20 06:31 UTC, watasuke102 commented
> Do you forget this?

I fixed, but forgot to push…

2022-08-20 06:46 UTC, Aki-7 approved these changes
Good job!!!

2022-08-20 06:46 UTC, merged