Add popup window
zigen-project/zen pull request #108
Opened 2022-08-17 08:28 UTC by shierote

## Context

## Summary

## How to check behavior

2022-08-21 05:21 UTC, Aki-7 commented
Current popup implementation is still not completive. I don't want to merge this without knowing what feature about popup is implemented, and what feature is still remained to be implemented.
For example, https://github.com/zigen-project/zen/issues/111.

At least, the pointer events to popup surfaces are not implemented, right?

2022-08-21 05:45 UTC, Aki-7 requested changes

2022-08-21 05:45 UTC, Aki-7 commented on zen/render-2d.c
> +    zn_render_2d_view_popups(view, renderer);
I think popups are a part of view, so `zn_render_2d_view_popups` seems better to be called in `zn_render_2d_view`.

2022-08-21 05:45 UTC, Aki-7 commented on zen/render-2d.c
> +    struct wlr_renderer *renderer, const struct wlr_fbox *box)
```suggestion
    struct wlr_renderer *renderer, const struct wlr_box *box)
```

We should use `wlr_box` for textural calculation (because texture takes discrete position value), `wlr_fbox` for view/cursor positioning, view/cursor intersection, etc (because output's scale factor(float) will be multiplied to view/cursor position).

Please fix other part accordingly.

2022-08-21 05:45 UTC, Aki-7 commented on zen/render-2d.c
> +  memcpy(surface_box, &box, sizeof(box));
```suggestion
  surface_box.x = view->x + surface_x;
  surface_box.y = view->y + surface_y;
  surface_box.width = surface->current.width;
  surface_box.height = surface->current.height;
```

2022-08-21 05:45 UTC, Aki-7 commented on zen/render-2d.c
> +      wlr_surface, zn_render_wlr_surface_iterator, &data);
Good!

2022-08-21 05:45 UTC, Aki-7 commented on zen/render-2d.c
> +    struct wlr_renderer *renderer, const struct wlr_fbox *box)
@watasuke102 FYI

2022-08-21 07:25 UTC, Aki-7 commented on zen/render-2d.c
> +    struct wlr_renderer *renderer, const struct wlr_fbox *box)
I may have made a slight mistake. The box argument here might be ok with `wlr_fbox`. Instead, it would be better to adapt the `transform` and `scale` of the wlr_output as done in
https://github.com/swaywm/sway/blob/5543acff06981639086bc9a0fc9b608796a23e84/sway/desktop/render.c#L132-L170
before passing them to wlr_render_texture.

2022-08-24 07:21 UTC, Aki-7 requested changes

2022-08-24 07:21 UTC, Aki-7 commented on zen/render-2d.c
> +    struct wlr_surface *surface, int surface_x, int surface_y, void *user_data)
The function name seems arbitrary.

```suggestion
zn_render_2d_for_each_surface_iterator(
    struct wlr_surface *surface, int surface_x, int surface_y, void *user_data)
```

2022-08-24 07:21 UTC, Aki-7 commented on zen/render-2d.c
> +zn_render_surface_iterator(struct wlr_surface *surface,
The function name seems arbitrary.

```suggestion
zn_render_2d_render_surface_iterator(struct wlr_surface *surface,
```

2022-08-24 07:21 UTC, Aki-7 commented on zen/render-2d.c
> +    int surface_x, int surface_y, struct wlr_fbox *surface_box)
```suggestion
get_surface_fbox(struct wlr_surface *surface, struct zn_view *view,
    int surface_x, int surface_y, struct wlr_fbox *surface_box)
```
or
```suggestion
zn_render_2d_get_surface_fbox(struct wlr_surface *surface, struct zn_view *view,
    int surface_x, int surface_y, struct wlr_fbox *surface_box)
```

2022-08-24 07:21 UTC, Aki-7 commented on zen/render-2d.c
> +};
This may cause namespace conflicts in the future.

```suggestion
typedef void (*surface_iterator_func_t)(struct wlr_surface *surface,
    struct wlr_renderer *renderer, const struct wlr_fbox *box);

struct surface_iterator_data {
  surface_iterator_func_t iterator;

  struct zn_view *view;
  struct wlr_renderer *renderer;
};
```

2022-08-24 10:14 UTC, shierote commented
@Aki-7 Thank you for your review!
I fixed your comments and rechecked the behaviors.

2022-08-24 14:23 UTC, Aki-7 approved these changes
LGTM!

2022-08-24 14:23 UTC, watasuke102 approved these changes

2022-08-24 23:02 UTC, merged