Focus view
zigen-project/zen pull request #124
Opened 2022-08-24 12:29 UTC by watasuke102

## Context

Focus / unfocus to view. So far, change is only that it appears brighter than the other views.

## Summary

Using `wlr_xdg_toplevel_set_activated` and `wlr_xwayland_surface_activate`

## How to check behavior

1. start zen more than 2 clients
2. click each client; the view is activated
3. click out of the view; the view is inactivated

2022-08-25 04:47 UTC, Aki-7 requested changes

2022-08-25 04:47 UTC, Aki-7 commented on include/zen/scene/board.h
> +  struct wl_listener focus_listener;
unused

2022-08-25 04:47 UTC, Aki-7 commented on include/zen/scene/scene.h
> +  struct wl_listener destroy_active_view_listener;
Should listen `unmap`. Unmap always happens before beeing destroyed.

2022-08-25 04:47 UTC, Aki-7 commented on zen/scene/view.c
> +  }
We should not assume `self` is NULL
```suggestion
  self->impl->focus(self);
```

2022-08-25 04:47 UTC, Aki-7 commented on zen/scene/view.c
> +  }
```suggestion
  self->impl->unfocus(self);
```

2022-08-25 04:47 UTC, Aki-7 commented on zen/input/pointer.c
> +  }
Sway do this before `wlr_seat_pointer_notify_button`. Is there any reason to change the order?

2022-08-25 04:47 UTC, Aki-7 commented on include/zen/scene/scene.h
> +  struct zn_view* active_view;
```suggestion
  struct zn_view* focus_view;
```

Do we have to use different term, `active` and `focus`?

2022-08-25 04:47 UTC, Aki-7 commented on zen/input/pointer.c
> +  }
I think it's more safe to call `zn_scene_set_active_view` here and call `zn_view_(focus|unfocus)` inside the `zn_scene_set_active_view`.

2022-08-25 04:47 UTC, Aki-7 commented on zen/xwayland-view.c
> +  wlr_xwayland_surface_activate(self->wlr_xwayland_surface, true);
```suggestion
  wlr_xwayland_surface_activate(self->wlr_xwayland_surface, true);
  wlr_xwayland_surface_restack(surface, NULL, XCB_STACK_MODE_ABOVE);
```

We don't need `wlr_xwayland_surface_restack`?

2022-08-25 04:47 UTC, Aki-7 commented on include/zen/scene/view.h
> +  void (*unfocus)(struct zn_view *view);
```suggestion
  void (*set_activated)(struct zn_view *view, bool activated);
```

I think it is more in line with the actual situation to think of `activate` as one of the processes of `focus`.
`focus` has other processes such as reordering the views.

A single method with a boolean value is more simple, I think.

2022-08-25 04:56 UTC, watasuke102 commented on zen/xwayland-view.c
> +  wlr_xwayland_surface_activate(self->wlr_xwayland_surface, true);
I'm going to implement about restack as another PR.

2022-08-25 07:23 UTC, Aki-7 commented
Please resolve the conflicts, then I'll look into this.

2022-08-29 14:00 UTC, watasuke102 commented
close; this feature is implemented by #134

2022-08-29 14:00 UTC, closed without merging