fix #133
zigen-project/zen pull request #139
Opened 2022-08-31 07:46 UTC by watasuke102

## Context

See #133

## Summary

add `zn_cursor_set_xcursor()`.

## How to check behavior

None

2022-08-31 08:48 UTC, watasuke102 commented
This PR doesn't have enough consideration

2022-09-02 06:13 UTC, Aki-7 requested changes

2022-09-02 06:13 UTC, Aki-7 commented on zen/cursor.c
> +zn_cursor_set_xcursor(struct zn_cursor* self, char* name)
You suppose that
if (zn_cursor::surface && zn_cursor::texture) : a client set the cursor's surface.
if (zn_cursor::surface && !zn_cursor::texture) : never happen.
if (!zn_cursor::surface && !zn_cursor::texture) : using xcursor
if (!zn_cursor::surface && !zn_cursor::texture) : a client unset cursor's surface (invisible cursor)

Then zn_cursor's public methods should be safe about the consistency above.
Suppose a programmer writes the following code.
```c
zn_cursor_set_surface(cursor, surface, hx, hy);

... later ...

zn_cursor_set_xcursor(cursor, "left_ptr");
```

With current implementation, zn_cursor::surface and ::texture will not be null neither. But doesn't mean using a  surface given by a client.

Your current code works well because you call zn_cursor_set_xcursor and zn_cursor_set_surface at the same time, but it's not safe. Both methods should keep this consistency.

2022-09-02 06:15 UTC, Aki-7 commented on zen/cursor.c
> +zn_cursor_set_xcursor(struct zn_cursor* self, char* name)
Thus you don't have to call this two methods every time
```c
  zn_cursor_set_surface(self, NULL, 0, 0);
  zn_cursor_set_xcursor(self, "left_ptr");
```
instead, just
```c
  zn_cursor_set_xcursor(self, "left_ptr");
```

2022-09-02 08:37 UTC, Aki-7 commented
The code seems ok, but I met an error log.
```
*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

2022-09-02 09:35 UTC, watasuke102 commented
I can't reproduce that. Can you tell how it occured in detail?

2022-09-02 10:47 UTC, watasuke102 commented
Can I leave this as another issue? It reproduced in my environment, but it's hardly.

2022-09-02 12:50 UTC, Aki-7 commented
I found the cause.

2022-09-02 12:52 UTC, Aki-7 commented on zen/cursor.c
> +  zn_cursor_damage_whole(self);
Here, texture has been destroyed but not NULL, and it gets wrong fbox of the cursor.

2022-09-02 12:57 UTC, Aki-7 commented on zen/cursor.c
> -
Here is another problem. Removing this ,  `zn_cursor_damage_whole` will be called in succession.

Originally, the former `zn_cursor_damage_whole` adds a damage of previous surface, and the later one adds a damage of next surface.
We can see from this that we have to keep `zn_cursor::width` and `::height` to add damage of previous surface.

2022-09-02 13:05 UTC, Aki-7 commented on zen/cursor.c
> +      image->width * 4, image->width, image->height, image->buffer);
With this implementation, as `zn_cursor_set_xcursor` will be called every time the cursor moves on the screen where no view exists, `zn_cursor::texture` will be created and destroyed again and again in vain.

As `wlr_xcursor_manager_get_xcursor` returns the same pointer for the same "name", you should check whether the next xcursor is the same as the current xcursor.

2022-09-02 15:03 UTC, Aki-7 requested changes
I found a bug, 

Reproduce step,
1. start google-chrome
2. close the google chrome by pressing the closing-tab button.

I submit few reviews, but I review remaining part again after solving this bug.

2022-09-03 00:57 UTC, watasuke102 commented
probably related #112

2022-09-03 04:23 UTC, Aki-7 commented
Maybe, but compositor crashing is not acceptable.
If so, please fix #112 first, or within this PR.

2022-09-03 14:14 UTC, watasuke102 commented
This occured because cursor->texture is different from cursor->surface's texture, so I think before method (cursor->texture contains xcursor's texture, fetch surface's texture every render) is better.

I think rebuilding this PR is may better...

2022-09-04 09:22 UTC, closed without merging