Move view
zigen-project/zen pull request #145
Opened 2022-09-04 11:01 UTC by watasuke102

## Context

Move the view by the cursor.

## Summary

Add `zn_cursor_grab_move`.

## How to check behavior

1. start zen and some wayland client
2. drag the top of the view - the view is moved
3. drag between screens - the view is moved between boards

2022-09-06 02:33 UTC, watasuke102 commented
Solve #147 at first

2022-09-08 20:17 UTC, Aki-7 requested changes

2022-09-08 20:17 UTC, Aki-7 commented on zen/scene/view.c
> +  zn_view_damage_whole(self);
It's wired to call this here.
As changing the view's board without changing its position is not a common operation, this function doesn't seem visual operation. I mean no one changes the view's position only by using this function. So, damaging the view area after only changing the view's board doesn't make sense to me.

My suggestion is to create a function like,
```c
/** board can be NULL only when unmap */
void
zn_view_move(struct zn_view* self, struct zn_board* board, double x, double y) {
  zn_view_damage_whole(self);

  if (board != self->board) {
    if (self->board) { /* remove */ }
    if (board) { /* assign */}
  }
  
  self->x = x;
  self->y = y;

  if (self->impl->configure) {
    self->impl->configure(self, x, y);
  }

  zn_view_damage_whole(self);
}
```

2022-09-08 20:17 UTC, Aki-7 commented on zen/cursor.c
> +    self->grab->interface->cancel(self->grab);
Are you trying to make sure that non-default grabs are not used when there is no screen?

2022-09-08 20:17 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  zn_cursor_set_xcursor(self->base.cursor, "left_ptr");
A xcursor is set also in `zn_cursor_end_grab`, which function, `zn_cursor_grab_move_end` or `zn_cursor_end_grab`, has a responsibility to set cursor image?

2022-09-09 02:38 UTC, watasuke102 commented on zen/input/cursor-grab-move.c
> +  }
Please read `How to check behavior`.

> drag between screens - the view is moved between boards

2022-09-09 05:24 UTC, watasuke102 commented on zen/cursor.c
> +    self->grab->interface->cancel(self->grab);
yes

2022-09-09 06:45 UTC, watasuke102 commented on zen/cursor.c
> +    wlr_seat_pointer_enter(seat, surface, view_x, view_y);
What do you mean?

2022-09-09 08:55 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  }
What about the case while switch board (using short cut) while moving?

2022-09-09 14:51 UTC, Aki-7 commented on zen/cursor.c
> +    wlr_seat_pointer_enter(seat, surface, view_x, view_y);
With the previous code, if the grab ends and the pointer enters a surface, the surface texture is not set.
If the client sends a "set cursor" request immediately after sending a "pointer enter" event, there is no problem, but if the client will not send a "set cursor" request, I though we should show a default cursor.

2022-09-09 15:25 UTC, Aki-7 commented on zen/cursor.c
> +    self->grab->interface->cancel(self->grab);
That's a good very good constraint!
I would like you to add a comment about that.

2022-09-09 19:34 UTC, Aki-7 requested changes

2022-09-09 19:34 UTC, Aki-7 commented on zen/cursor.c
> +    struct zn_cursor* self, double* view_x, double* view_y)
```suggestion
static struct wlr_surface*
zn_cursor_get_pointing_surface(
    struct zn_cursor* self, double* surface_x, double* surface_y)
```

2022-09-09 19:34 UTC, Aki-7 commented on include/zen/input/cursor-grab-move.h
> +  struct zn_board* init_board;
Please handle the destruction of the board.

I think we don't need to reset the position when canceled though.

2022-09-09 19:34 UTC, Aki-7 commented on include/zen/input/cursor-grab-move.h
> +  struct zn_view* view;
```suggestion
  struct zn_view* view; // nonnull
```

2022-09-09 19:34 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  wl_list_remove(&self->view_unmap_listener.link);
```suggestion
  wl_list_remove(&self->view_unmap_listener.link);
  wl_list_remove(&self->prev_screen_destroy_listener.link);
```

2022-09-09 19:34 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  }
With this constraint: while a non-default grab is in use, the cursor's screen will not be NULL, `cursor->screen` must not be NULL here.

2022-09-09 19:34 UTC, Aki-7 commented on zen/scene/view.c
> +    // new_board is NULL only when unmapping
This comment should be at the prototype declaration.
(I added another review  about this)

2022-09-09 19:34 UTC, Aki-7 commented on zen/scene/view.c
>    wl_list_insert((&board->view_list)->prev, &self->link);
```suggestion
  zn_view_move(self, (board->width - fbox.width) / 2,
      (board->height - fbox.height) / 2, board);
```

2022-09-09 23:51 UTC, watasuke102 commented on include/zen/scene/view.h
> +    struct zn_view *self, double x, double y, struct zn_board *new_board);
Originally, I think `zn_view_move` only updates the position of the view, so updating board is secondaly task. Arguments about position seem more important for me, and my prefer important argument should place first, so I added argument of the board to the last.

2022-09-10 00:18 UTC, watasuke102 commented on include/zen/input/cursor-grab.h
> +  // called when zn_cursor::screen is assigned NULL
> zn_cursor_grab::cancel is the interface to cancel the current grab operation, not the interface which is called when zn_cursor::screen is assigned NULL.

That's true, but I believe it is also correct to call `zn_cursor_grab::cancel` when `zn_cursor::screen` is assigned NULL. I mean with this comment is that this interface will be called when screen is assigned NULL, not that this is the only case.

And, I wonder that problems about screen's constraint is solved by calling `zn_cursor_grab::cancel` when `zn_cursor::screen` is assigned NULL.

2022-09-11 16:05 UTC, Aki-7 requested changes

2022-09-11 16:05 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  move_grab_cancel(grab);
In my opinion, If boards are switched while a view is being moved, it is better to move the view to the board that is displayed and continue the move operation.

```suggestion
  struct zn_cursor_grab_move* self = zn_container_of(grab, self, base);
  struct zn_board* board =
      zn_screen_get_current_board(self->base.cursor->screen);
  zn_view_move(self->view, board, self->base.cursor->x + self->diff_x,
      self->base.cursor->y + self->diff_y);
```

2022-09-12 02:42 UTC, watasuke102 commented on zen/input/cursor-grab-move.c
> +  // the board which the view is located is changed
> Not limited to when the board on which the view is located is changed

What is the case for example?

2022-09-12 06:37 UTC, Aki-7 commented on zen/input/cursor-grab-move.c
> +  // the board which the view is located is changed
An example would be when a new view is created during the move operation.
You may want to raise the moving view above the newly generated view.

But my point has nothing to do with what the example is. The point is to clarify the responsibility of this `zn_cursor_grab::rebase` interface.
Since we are providing polymorphism by introducing a grab, the rebase of default_grab and the rebase of move_grab must handle the same situation. That situation is, as the name `rebase` suggests, repositioning the cursor.
What kind of situation is meant by repositioning the cursor is a matter of debate, and I hope that a common understanding will emerge in the course of development, but at least I don't think it refers only to switching boards.
In other words, it is the role of screens to handle board switching, and the function rebase of zn_cursor should be used to realize board switching, and zn_cursor itself should not know as much as possible that the board has switched, etc.

Let me explain from a different perspective. But I believe this is just a more specific example of what I mentioned above.
If we make the rebase of move_grab only for when switching boards, that means that it would be a mistake to call `cursor->grab->interface->rabase()` at any other time even for default garb. Or you need to make sure that `cursor->grab->interface` matches the interface of move_grab before calling it. This would violate the concept of polymorphism.

Some may argue that using polymorphism is a bad idea. That is certainly a possibility. But we are able to describe cursor behavior relatively safely with it, which is probably why other windowing systems also use this polymorphism.

2022-09-12 10:57 UTC, Aki-7 approved these changes
That's a lot of work, great job!

2022-09-12 11:36 UTC, Aki-7 approved these changes

2022-09-12 11:36 UTC, merged