Add background images
zigen-project/zen pull request #152
Opened 2022-09-11 10:31 UTC by liwii

## Context
In the current `zen-desktop`, the background is filled with one green-ish color. With a background image, the system would be more attractive to the users.
## Summary
Install the background images provided by @rtr-dnd and draw it on the screen. If the screen size ratio does not match the image size ratio, the image is scaled with aspect-fill manner.
![image_123927839](https://user-images.githubusercontent.com/26531068/189522607-c28a88c5-6f89-4697-ab68-be28a1ba5ee3.JPG)
## How to check behavior
Run `zen-desktop -s weston-terminal` and see if the background image is properly set. You can also test the other bundled background images by changing the line in https://github.com/zigen-project/zen/compare/main...liwii:bg?expand=1#diff-d6c974d638e0e2ea1f88ab4bb8e67b78b22a6aa636536a72467d9b39bb9defe0R14.  
If needed, change the screen orientation and the scale like the comment in #121 and test it again.

2022-09-11 10:51 UTC, watasuke102 requested changes

2022-09-11 10:51 UTC, watasuke102 commented on zen/screen-renderer.c
> +}
When loading background image file is failed in some reasons (ex. file not found), `bg_texture` becomes NULL, and crash zen on rendering. Please check `bg_texture` at first.

2022-09-11 10:58 UTC, liwii commented on zen/screen-renderer.c
> +}
Fixed, thanks for the catch!!

2022-09-11 11:21 UTC, watasuke102 submitted a review, later dismissed
Nice change!

2022-09-11 13:21 UTC, Aki-7 requested changes
Did all the images display well?
(Sorry I didn't confirm that for myself)

2022-09-11 13:21 UTC, Aki-7 commented on zen/screen-renderer.c
> +        (int)(bg_texture->height * output_width / (double)bg_texture->width);
```suggestion
        bg_texture->height * output_width / bg_texture->width;
```

2022-09-11 13:21 UTC, Aki-7 commented on zen/screen-renderer.c
> +        screen, renderer, server->scene->bg_texture);
How about iterating the damage rectangles in `zn_screen_renderer_render_background`?
All other `zn_screen_renderer_render_*` functions do so.

```c
zn_screen_renderer_render_background(
    struct zn_screen *screen, struct wlr_renderer *renderer, 
    struct wlr_texture *bg_texture, pixman_region32_t *screen_damage) {
  ...
  for (int i = 0; i < rect_count; i ++) {
    zn_screen_renderer_scissor_output(output, &rects[i]);
    wlr_renderer_clear(renderer, (float[]){1.0, 1.0, 10, 1});
    if (bg_texture)
      wlr_render_texture_with_matrix(renderer, bg_texture, matrix, 1.0f);
  }
}
```

2022-09-13 15:54 UTC, liwii commented
Logo
![5A11143B-3732-49E7-B5F3-68242BEA56DF](https://user-images.githubusercontent.com/26531068/189948764-360b23a7-30a5-449c-a908-438238929bd5.jpeg)
Tricolor
![1453BDC0-EB0A-4B41-993C-1E72E5A4D377](https://user-images.githubusercontent.com/26531068/189948434-c217dae0-93a0-4e6d-ab4e-a9bcbafdd435.jpeg)
Blue
![364B4E99-9369-42C6-BB2F-D080491F8C4F](https://user-images.githubusercontent.com/26531068/189948416-221230e5-ac16-4b07-a8f4-786f4a4893d1.jpeg)
Gray
![CB1E919C-7685-4A07-96D9-87BADF9A65E2](https://user-images.githubusercontent.com/26531068/189948425-09d8af24-4f19-4839-b2f3-6d957bbdf2b6.jpeg)

They look fine to me

2022-09-13 15:57 UTC, liwii commented on zen/scene/scene.c
> +void
Thanks, it should be better to mark `static` when possible.

2022-09-13 16:26 UTC, liwii commented
Thanks for the review. I fixed some, and I'll deal with the unresolved comments tomorrow.

2022-09-14 04:23 UTC, Aki-7 commented on zen/screen-renderer.c
> +        (int)(bg_texture->height * output_width / (double)bg_texture->width);
Can you also fix the almost identical code a few lines above?

2022-09-14 04:24 UTC, Aki-7 commented
My suggestions are not meant to be a final code. I would like you to edit them in your editor accordingly. 
There are formatting errors with the current commit. Sorry for the CI misconfiguration (fixed in #158), but I would like you to fix them and rebase to the main branch to apply the new CI configuration.

And I added a new comment https://github.com/zigen-project/zen/pull/152#discussion_r970293056.

2022-09-17 02:33 UTC, liwii commented on zen/screen-renderer.c
> +        (int)(bg_texture->height * output_width / (double)bg_texture->width);
Done.

2022-09-17 03:48 UTC, liwii commented on zen/scene/scene.c
> +      cairo_image_surface_create_from_png(background_png);
It seems that  `wlr_texture_from_pixels` allcates its own buffer and copies the data to it.

https://github.com/swaywm/wlroots/blob/0855cdacb2eeeff35849e2e9c4db0aa996d78d10/render/wlr_texture.c#L32
https://github.com/swaywm/wlroots/blob/9579d62a160821a107763325a515d3aee0a1e158/types/wlr_buffer.c#L483

I would destroy the surface immediately after the wlr texture creation and deal with `wlr_texture` in `zn_scene_destroy`.

2022-09-17 03:51 UTC, liwii commented on zen/scene/scene.c
> +  if (surface == NULL) {
Fixed. Thanks for pointing it out.

2022-09-17 03:52 UTC, liwii commented on zen/screen-renderer.c
> +        screen, renderer, server->scene->bg_texture);
It looks cleaner. Thanks for the suggestion.

2022-09-17 03:53 UTC, liwii commented
Now I think the code is ready for review again!!

2022-09-17 05:36 UTC, watasuke102 commented on zen/scene/scene.c
> +  }
Can you use `if (status != CAIRO_STATUS_SUCCESS)` ?

2022-09-17 09:08 UTC, Aki-7 requested changes

2022-09-17 09:08 UTC, Aki-7 commented on meson.build
> +endif
Build fails when `default-wallpaper` option is false.

2022-09-18 01:02 UTC, liwii commented on meson.build
> +zen_inc = include_directories('include', '.')
Thanks, I moved `zen-config.h.meson` to `zen/` and let `zen/meson.build` to directly include the configuration file.

2022-09-18 01:04 UTC, liwii commented on meson.build
> +endif
Now it assigns "" to `DEFAULT_WALLPAPER` when the option is false (this case should be properly handled in the source code) .

2022-09-18 03:33 UTC, Aki-7 approved these changes
It's motivational!

2022-09-18 12:46 UTC, merged