resize view
zigen-project/zen pull request #156
Opened 2022-09-13 09:03 UTC by watasuke102

## Context

Resize the view by the cursor.

## Summary

Add `zn_cursor_grab_resize`.

## How to check behavior

1. start zen and some wayland client
2. drag the corner of the view
3. the size of the view is changed following the cursor

2022-09-16 16:32 UTC, Aki-7 requested changes
1. I think the calculation of view size and coordinates when resizing is too complicated. Please consider if it can be refactored.

2. Please rebase to main branch. I don't trust git auto merging / rebasing.

2022-09-16 16:32 UTC, Aki-7 commented on include/zen/input/cursor-grab-resize.h
> +#ifndef ZN_CURSOR_GRAB_RESIZE_H
Please use `#pragma once`

2022-09-16 16:32 UTC, Aki-7 commented on include/zen/scene/view.h
> +
```suggestion
```

2022-09-16 16:32 UTC, Aki-7 commented on include/zen/scene/view.h
> + */
```suggestion
/** 
 * set window's size (corresponding to the result of view_get_window_fbox)
 * @retval serial for resize event
 */
```

2022-09-16 16:32 UTC, Aki-7 commented on zen/scene/view.c
> +  zn_view_damage_whole(self);
This seems unnecessary.

2022-09-16 16:32 UTC, Aki-7 commented on include/zen/scene/view.h
> +  void (*set_position)(struct zn_view *view, double x, double y);  // nulable
I feel it is not a good idea to separate `configure` into `set_size` and `set_position`.
I think that when you have the resizing process revised in this PR, you will need to atomically change the size and position of the view.

2022-09-16 16:32 UTC, Aki-7 commented on zen/xdg-toplevel-view.c
> +      self->base.resize_status.requested_box.y + dy);
The actual change of view position should be at the time of `commit`. Until `commit`, the surface state is pending and should not be reflected in the rendering.

2022-09-16 16:32 UTC, Aki-7 commented on zen/xdg-toplevel-view.c
> +      &self->wlr_xdg_toplevel->events.request_resize, &self->resize_listener);
Please register this listener on `map`.

2022-09-17 00:07 UTC, watasuke102 commented on include/zen/scene/view.h
> +  void (*set_position)(struct zn_view *view, double x, double y);  // nulable
I don't think so.
xdg_toplevel doesn't provide the function of updating its position, so they don't seem the same. Also, you reported before that the size of `weston-terminal` is changed on moving the view, it may occured because `configure` also updates the **size**, despite unnecessary. Separating these will solve this problem.

2022-09-17 12:12 UTC, watasuke102 commented
> Please consider if it can be refactored

I can't

2022-09-18 12:11 UTC, Aki-7 requested changes
Nice refactoring!

2022-09-18 12:11 UTC, Aki-7 commented on include/zen/xwayland-view.h
> +  struct wl_listener resize_listener;
Will not implement actual resizing for xwayland-view?

2022-09-18 12:11 UTC, Aki-7 commented on zen/input/cursor-grab-resize.c
> +}
In the case of resizing, it would be more natural to cancel at rebasing. You can ask other developers about this.

2022-09-18 12:11 UTC, Aki-7 commented on zen/input/cursor-grab-resize.c
> +      self->view, self->view->board, self->init_view_x, self->init_view_y);
This seems needless because `set_size` will trigger the next commit with the resized surface, and then, at the time of commit, the view's position will be moved.

2022-09-18 12:11 UTC, Aki-7 commented on zen/input/cursor-grab-resize.c
> +{
```suggestion
{
  zn_cursor_set_xcursor(self->base.cursor, "left_ptr");
```

2022-09-18 12:26 UTC, watasuke102 commented on include/zen/xwayland-view.h
> +  struct wl_listener resize_listener;
I eager to implement this, but I don't have any way to test it (x client is't able to resize now). If it is allowed, I'll leave FIXME comment.

2022-09-18 12:34 UTC, Aki-7 commented on include/zen/xwayland-view.h
> +  struct wl_listener resize_listener;
I see,
> I'll leave FIXME comment.

It's good enough!

2022-09-19 05:36 UTC, Aki-7 requested changes

2022-09-19 05:36 UTC, Aki-7 commented on zen/xdg-toplevel-view.c
> +  self->base.resize_edges = 0;
I think `resize_edges` should not be reset (and should not set a value in `resize_grab_motion`).

Consider the case where the events(→) and requests(←) happen in the following order,
→ configure ( = set_size)
→ configure ( = set_size)
← commit (using the data of the first configure event)
← commit (using the data of the second configure event)

the last commit will not be treated properly.

2022-09-19 08:25 UTC, Aki-7 commented on include/zen/scene/view.h
> +    enum { None, Resizing, Canceled } mode;
This still does not resolve the case I mentioned in https://github.com/zigen-project/zen/pull/156#discussion_r973874231
The solution is more simple, just previous `bool resizing` seems good to me.

2022-09-19 08:28 UTC, Aki-7 commented on include/zen/scene/view.h
> +    enum { None, Resizing, Canceled } mode;
And this enum can cause namespace conflict. Please use the UPPER_CASE, global-unique name for enum members.

2022-09-19 08:32 UTC, watasuke102 commented on include/zen/scene/view.h
> +    enum { None, Resizing, Canceled } mode;
> still does not resolve

What is the case you thinking? Unless sending two or more configure event, the mode isn't changed, so I thought it works well.

> bool resizing seems good

How can it process canceling (update position)? On previous code, `resizing` is set false when canceling.

2022-09-19 09:35 UTC, Aki-7 approved these changes
Looks Good To Me!

2022-09-19 09:46 UTC, Aki-7 approved these changes

2022-09-19 09:46 UTC, merged