add popup damage
zigen-project/zen pull request #157
Opened 2022-09-13 15:47 UTC by shierote

## Context

#116, #122 

## Summary

- Added xdg_shell's popup damage.
- This allows, for example, right-clicking on a wayland client to display/hide the popup. Details of what can now be done are added in the "How to check behavior" section.
- Added view_child struct to handle damage.

## How to check behavior
The following behaviors can be checked with the Wayland clients (e.g., `weston-terminal` `weston-flower`)
- showing popup
  - When you right click on the view, a popup appears around the cursor.
    - The requirement that if the cursor is around the edge of the screen, the popup appear inside the screen, is todo.
  - When you right click anywhere else, the previous popup disappears and a new popup appears around the cursor.
- hiding popup
  - (right/left) click elsewhere in the view
  - close the view
  - start `move`
  - focus/restack another view

- The behavior related to board is not defined.
  - When the view is focused during the board operation, the popup will remain.
  - When the view is unfocused during the board operation, the popup will disappear.

NOTE:
Below are the TODOs.
- popup's popup (popup tree)
  - handle the case that view_child's parent(view_child) exists.
- if the cursor is around the edge of the screen, the popup appear inside the screen.
- (subsurface)

2022-09-18 14:07 UTC, Aki-7 requested changes

2022-09-18 14:07 UTC, Aki-7 commented on zen/scene/view-child.c
> +      self->view->board == NULL || self->view->board->screen == NULL)
`self->view->board` is non null.

2022-09-18 14:18 UTC, shierote commented on zen/xdg-toplevel-view.c
> +  wl_list_remove(&self->map_listener.link);
This has been replaced to remove the members of `struct zn_xdg_toplevel_view` (`include/zen/xdg-toplevel-view.h`) in the reverse order of its definition. There is no technical reason.

2022-09-18 14:19 UTC, shierote commented on include/zen/xdg-popup.h
> +  struct wl_listener unmap_listener;  //
thx!

2022-09-18 14:21 UTC, shierote commented on zen/scene/view-child.c
> +  if (zn_view_child_is_mapped(self)) zn_view_child_damage(self);
That seems simple and nice to me!

2022-09-18 14:25 UTC, shierote commented on zen/scene/view-child.c
> +  self->mapped = false;
Are you implying that I should delete the `self->mapped = false` line?

2022-09-18 14:39 UTC, Aki-7 commented on zen/scene/view-child.c
> +  self->mapped = false;
Sorry, I wanted to say `zn_view_chile_unmap`.
```suggestion
  zn_view_child_unmap(self);
```

2022-09-18 15:04 UTC, watasuke102 requested changes

2022-09-18 15:49 UTC, shierote commented on zen/xdg-toplevel-view.c
> +zn_xdg_toplevel_view_new_popup(struct wl_listener* listener, void* data)
This follows other code conventions.
However, I agree that it is difficult to recognize it as a handler, so I will rename the other parts of the code as well. Thanks.

2022-09-18 15:59 UTC, shierote commented on zen/scene/view-child.c
> +  self->mapped = false;
I understand! Good idea, thanks!!

2022-09-18 16:34 UTC, shierote commented on zen/xdg-toplevel-view.c
> +zn_xdg_toplevel_view_new_popup(struct wl_listener* listener, void* data)
I unified all handler names with *_handler in https://github.com/zigen-project/zen/pull/157/commits/b549b1e28fb42e8face57132df69ac6397befe03. check it out.

2022-09-18 16:37 UTC, shierote commented
I fixed all review points. thx!
Also, I took this opportunity to unify all handler names with *_handler in https://github.com/zigen-project/zen/commit/b549b1e28fb42e8face57132df69ac6397befe03. check it out.

2022-09-18 18:46 UTC, Aki-7 commented
It's me who started to use `*_handler`, but now I think `handle_*` is better, because in the object oriented programming, the method should be basically verbs.
Could you rewrite b549b1e with `handle_*`? It's very good timing to fix it.

2022-09-19 00:42 UTC, shierote commented
@Aki-7 
> It's me who started to use *_handler, but now I think handle_* is better, because in the object oriented programming, the method should be basically verbs.

I fixed it.

2022-09-19 01:23 UTC, watasuke102 approved these changes
_LGTM_

2022-09-19 05:16 UTC, Aki-7 approved these changes
Looks good to me!

2022-09-19 06:30 UTC, merged