Configure bg images with .config/zen-desktop/config.toml
zigen-project/zen pull request #160
Opened 2022-09-19 04:27 UTC by liwii

## Context
To realize user-specific configuration like #123, we need a way to give configuration data to zen-desktop after the build.

## Summary
Let users specify their background image with a `toml` config file.Following [XDG Base Directory Specification
](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), it first searches `$XDG_CONFIG_HOME/zen-desktop/config.toml`, then falls back to `$HOME/.config/zen-desktop/config.toml`.

## How to check behavior
- Create the following config file and save it as `$HOME/.config/zen-desktop/config.toml`. Note that only ** PNG images with RGBA format ** can be used as the background images for now.
```toml
[background]
image = "/path/to/your/image/file"
```
- Run `zen-desktop` and see if the change is reflected.

2022-09-19 06:29 UTC, Aki-7 commented
TIPS (for others who try this with their favorite image)

ImageMagick command
```
convert image.jpeg -define png:color-type=6 image.png
```

2022-09-19 07:47 UTC, watasuke102 requested changes

2022-09-19 07:47 UTC, watasuke102 commented on zen/config.c
> +zn_config_destroy(struct zn_config *self)
(nit) please add blank line.

```suggestion
}

void
zn_config_destroy(struct zn_config *self)
```

2022-09-19 07:55 UTC, watasuke102 commented on include/zen/config.h
> +void zn_config_destroy(struct zn_config* self);
and here
```suggestion
void zn_config_destroy(struct zn_config* self);

```

2022-09-19 08:09 UTC, Aki-7 requested changes
As you know, string (char*) allocates a certain contiguous part of memory region. For this reason, we need to be very careful when manipulating strings.

2022-09-19 08:09 UTC, Aki-7 commented on zen/server.c
> +  zn_config_destroy(self->config);
Basically, it is better to delete objects in the reverse order of their creation.
In this case, `zc_config_destroy` should be called after `sever_singleton = NULL`.

2022-09-20 14:28 UTC, liwii commented on include/zen/config.h
> +void zn_config_destroy(struct zn_config* self);
Thanks,
I think the editor is following `.clang-format` in the project. Is there any good config to do this eof new line thing?

2022-09-20 14:44 UTC, liwii commented on include/zen/config.h
> +  char* bg_image_file;
What's the intention of `const`? If it is eventually freed, it does not make sense to mark it as `const` (at least I feel a bit uncomfortable to do const to non-const casting in `free`.

2022-09-20 14:44 UTC, Aki-7 commented on include/zen/config.h
> +void zn_config_destroy(struct zn_config* self);
You are right, clang-format should handle this issue. 

>  Is there any good config to do this eof new line thing?

I don't know. Could you add a new config for this if any.

2022-09-20 15:35 UTC, liwii commented on zen/config.c
> +    config_home = strcat(homedir, "/.config");
Thanks for pointing that out. I didn't know that the directly manipulating the pointer obtained with `getenv()` is that dangerous.

2022-09-20 18:42 UTC, Aki-7 commented on include/zen/config.h
> +  char* bg_image_file;
Sorry, this is my mistake. I added "const" because DEFAULT_WALLPAPER was assigned to it, but as you said, we should not.

2022-09-20 19:09 UTC, Aki-7 commented on zen/config.c
> +  strcat(config_home, toml_file_partial_path);
Instead of `strcat` and `strcpy`, how about using `sprintf`?
This is a matter of preference, so if you don't like it, ignore it.
```c
if () {
   config_home = malloc(...);
   sprintf(config_home, "%s%s%s" ...);
else {
   config_home = malloc(...);
   sprintf(config_home, "%s%s" ...);
}
```

2022-09-24 07:18 UTC, liwii commented on zen/config.c
> +  strcat(config_home, toml_file_partial_path);
`sprintf` looks much cleaner. I fixed the code to use it. Thanks.

2022-09-24 07:35 UTC, watasuke102 requested changes

2022-09-24 07:35 UTC, watasuke102 commented on zen/config.c
> +  }
Accessing the released resource (`config_home`)

2022-09-24 07:35 UTC, watasuke102 commented on zen/config.c
> +  }
At this timing, `self->bg_image_file` has duplicated `DEFAULT_WALLPAPER` (by `zn_config_set_default`), so calling `free()` is required.

2022-09-24 08:59 UTC, Aki-7 reviewed
I left a few minor comments, but basically I think it is good except for the part of watasuke's comment.

2022-09-24 08:59 UTC, Aki-7 commented on zen/config.c
> +    zn_warn("config.toml not found in %s\n", config_home);
It could be for reasons other than the file not existing.

```suggestion
    zn_warn("Failed to open %s\n", config_home);
```

2022-09-24 09:00 UTC, Aki-7 commented on zen/config.c
> +    zn_warn("Could not get the toml table");
I think it's better to use words like "Fail" and "Error" as much as possible, because they are easy to search.
```suggestion
    zn_warn("Failed to get the toml table");
```

2022-09-26 01:00 UTC, watasuke102 approved these changes
**_LGTM_**

2022-09-26 03:04 UTC, Aki-7 approved these changes
Looks good to me!

2022-09-27 14:25 UTC, watasuke102 submitted a review, later dismissed

2022-09-27 14:42 UTC, watasuke102 approved these changes

2022-09-27 14:45 UTC, Aki-7 approved these changes

2022-09-27 14:45 UTC, merged