add key binding for switching virtual terminal
zigen-project/zen pull request #163
Opened 2022-09-20 06:56 UTC by watasuke102

## Context

At other DE, when press Ctrl+Alt+F1~, it switches to virtual terminal (tty).

## Summary

Implement switching vt by `wlr_session_change_vt`

## How to check behavior

1. start zen
2. press Ctrl+Alt+F([1-9]|10)
3. switch to virtual terminal

2022-09-20 12:29 UTC, shierote approved these changes

2022-09-20 12:29 UTC, shierote commented on zen/scene/scene.c
> +  const unsigned int vt = key - KEY_F1 + 1;
do you need handling of cases where vt is less than 1?

2022-09-20 12:32 UTC, watasuke102 commented on zen/scene/scene.c
> +  const unsigned int vt = key - KEY_F1 + 1;
> vt is less than 1

What is the case? `zn_scene_switch_vt_handler` is registered to the range of F1-F10, so the range of values that `vt` takes is 1-10.

2022-09-20 12:53 UTC, shierote commented on zen/scene/scene.c
> +  const unsigned int vt = key - KEY_F1 + 1;
No case, but I asked just in case the argument `key` of this function is not necessarily `KEY_F1`~`KEY_F10`.

2022-09-20 12:58 UTC, shierote commented on zen/scene/scene.c
> +  const unsigned int vt = key - KEY_F1 + 1;
But of course, if the user calling this function can recall from the function name the contract that there are no other keys to pass to this function than `KEY_F1`~`KEY_F10`, then the case handle is not necessary.

2022-09-20 14:13 UTC, shierote submitted a review, later dismissed
nice change!

2022-09-20 14:18 UTC, Aki-7 requested changes
I don't think switching virtual terminal is the responsibility of `scene`, but of `main.c`.
It's like handling signals.

2022-09-20 14:19 UTC, Aki-7 commented on zen/scene/scene.c
> +  if (wlr_backend_is_multi(server->backend)) {
At the conclusion of the last discussion, wasn't it sufficient to check for the existence of `session` in the handler, rather than checking for `is_multi` here?

2022-09-20 14:24 UTC, watasuke102 commented on zen/scene/scene.c
> +  if (wlr_backend_is_multi(server->backend)) {
Yes, it seems enough. But there is no reason to setup useless keybind, I think.

2022-09-20 14:56 UTC, Aki-7 commented on zen/scene/scene.c
> +  if (wlr_backend_is_multi(server->backend)) {
I know what you feel. But at the same time, this handles useless (never happen) situation, that is the backend is not the multi backend. It seems more useless for me. This causes the developer to read the code to see if the backend may not be multi-backend, as we did a few days ago.

2022-09-21 08:46 UTC, Aki-7 reviewed
LGTM!

2022-09-21 08:46 UTC, Aki-7 commented on zen/scene/scene.c
> +#include <wlr/backend/multi.h>
```suggestion
```

2022-09-21 08:48 UTC, Aki-7 approved these changes

2022-09-21 08:48 UTC, merged