Show VR modal
zigen-project/zen pull request #295
Opened 2023-01-06 12:38 UTC by watasuke102

## Context

We want to show information like `You're in VR`

## Summary

Add `zn_vr_modal` using zigzag, and when the display system is switched, the modal is shown

## How to check behavior

Start zen, and remote display system. You can see the modal.

2023-01-06 15:46 UTC, liwii requested changes

2023-01-06 15:46 UTC, liwii commented on zen/screen/renderer.c
> +    if (!node->visible) {
Could you update the `visibility` in the constructor of `zn_power_menu_item_clock` and `zn_power_menu_item_logout` to make these component compatible with the new way of rendering?

2023-01-06 15:46 UTC, liwii commented on zen/ui/nodes/vr-modal.c
> +zn_vr_modal_render_headset_dialog(struct zn_vr_modal *self, cairo_t *cr,
How about moving the headset dialog to a different struct like `zn_vr_modal_headset_status`?

2023-01-06 15:46 UTC, liwii commented on include/zen/ui/zigzag-layout.h
> +struct zn_vr_modal;
Could you include `vr-moda.h` here?

2023-01-06 15:51 UTC, watasuke102 commented on include/zen/ui/zigzag-layout.h
> +struct zn_vr_modal;
I think that's needless; other header (like `include/zen/cursor.h`) doesn't include header.

2023-01-06 15:54 UTC, liwii commented on include/zen/ui/zigzag-layout.h
> +struct zn_vr_modal;
Got it, then could you remove the include of `menu-bar` and `screen` to align the style??

2023-01-06 17:08 UTC, liwii commented on zen/ui/nodes/vr-modal.c
> +zn_vr_modal_render_headset_dialog(struct zn_vr_modal *self, cairo_t *cr,
Ahh I see,

I think we can use `set_frame` every time `zigzag_node_update_texture` is called to realize a node which dynamically changing the size (sorry I should have implemented it in that way...)

In my opinion, even though the dialog itself does not have a click region, it is more natural to implement it as another struct.

I'll upload a small patch to the update_texture, could you try rewriting it with that small patch? (If you want to spend more time on the other parts of the project, I can work on it after this PR is merged!!)

2023-01-06 17:16 UTC, liwii commented on zen/ui/nodes/vr-modal.c
> +zn_vr_modal_render_headset_dialog(struct zn_vr_modal *self, cairo_t *cr,
#298

2023-01-07 00:05 UTC, watasuke102 commented on zen/ui/nodes/vr-modal.c
> +zn_vr_modal_render_headset_dialog(struct zn_vr_modal *self, cairo_t *cr,
nice!

2023-01-07 01:59 UTC, watasuke102 commented
@liwii I created `vr-modal` directory under `zen/ui/nodes/`. Do you want me to apply this change like this to `power-menu`? Or do you have any reason not to create subdirectory? (If so, I revert this change)

2023-01-07 03:21 UTC, liwii commented
Yeah there was no reason for the non-subdirectorty structure. If you could help me add the structure to `power-menu` that would be great!!

2023-01-07 03:43 UTC, Aki-7 reviewed
I left an issue https://github.com/zigen-project/zen/issues/301

2023-01-07 03:43 UTC, Aki-7 commented on zen/remote.c
> +    // you should emit `peer_list_changed` after setting session to zn_peer
I think the state of a peer (e.g. the peer has session or not) should be sent via like zn_peer::events::state_changed.

2023-01-07 03:58 UTC, liwii commented on zen/screen/renderer.c
> +  }
Yes, the `zigzag_node`s shouldn't have any dependencies on `board`

2023-01-07 08:27 UTC, Aki-7 reviewed
one more!

2023-01-07 08:33 UTC, Aki-7 approved these changes
```
    ___       ___       ___       ___   
   /\__\     /\  \     /\  \     /\__\  
  /:/  /    /::\  \    \:\  \   /::L_L_ 
 /:/__/    /:/\:\__\   /::\__\ /:/L:\__\
 \:\  \    \:\:\/__/  /:/\/__/ \/_/:/  /
  \:\__\    \::/  /   \/__/      /:/  / 
   \/__/     \/__/               \/__/
```

2023-01-07 08:34 UTC, merged