fix FT_Face destruction
zigen-project/zen pull request #297
Opened 2023-01-06 13:34 UTC by Aki-7

## Context

FT_Face create from a FT_Library will be destroyed when the FT_Library is destroyed.
Destroying both results in double free.

## Summary

Fix FT_Face destruction process.

## How to check behavior

2023-01-06 14:38 UTC, liwii requested changes
Thanks for catching it!! Just one comment...

2023-01-06 14:38 UTC, liwii commented on zigzag/src/layout.c
> -        &self->ft_font_face_key, ft_face, (cairo_destroy_func_t)FT_Done_Face);
I think `ft_font_face_key` is not used anymore, could you help me remove it?

2023-01-07 01:27 UTC, Aki-7 commented on zigzag/src/layout.c
> -        &self->ft_font_face_key, ft_face, (cairo_destroy_func_t)FT_Done_Face);
Thanks for pointing that out!

2023-01-07 03:17 UTC, liwii approved these changes

2023-01-07 03:43 UTC, merged