Pointer
zigen-project/zen pull request #98
Opened 2022-08-04 01:29 UTC by watasuke102

## Context

implement a part of #89 

## Summary

The cursor is moved corresponding with mouse input. For now, it ignores boundaries of screens and doesn’t jump to other screens.

## How to check behavior

1. start zen
2. move your mouse
3. the cursor is moved

2022-08-04 13:53 UTC, liwii commented on zen/cursor.c
> +zn_cursor_move_relative(struct zn_cursor* self, int dx, int dy)
Why is it named "relative"? It seems that on wlroot non-relative event is called with "absolute" but the relative one is just called "wlr_pointer_motion_event" (sorry if I'm pointing to a wrong line)

2022-08-04 14:00 UTC, watasuke102 commented on zen/cursor.c
> +zn_cursor_move_relative(struct zn_cursor* self, int dx, int dy)
Yes, at wlroots, it called `motion`, and non-relative event is called `absolute`. But I think giving contrasting name is good. (It is my preference, so if you have some reason to follow naming by wlroot, I will make change this)

2022-08-04 14:05 UTC, liwii commented on zen/cursor.c
> +zn_cursor_move_relative(struct zn_cursor* self, int dx, int dy)
Sounds good to me. I would say that if we won't use the "absolute" motion in the future it's reasonable to name it just `zgn_cursor_motion`. But otherwise, it is very good to show the contrast with naming.

2022-08-04 14:13 UTC, watasuke102 commented on zen/cursor.c
> +zn_cursor_move_relative(struct zn_cursor* self, int dx, int dy)
That's true.

2022-08-05 13:43 UTC, Aki-7 requested changes

2022-08-05 13:43 UTC, Aki-7 commented on include/zen/pointer.h
> +  struct wlr_pointer* wlr_pointer;
What is this member for? If you are using this member in the next pull request, it's ok to keep this.

2022-08-05 13:43 UTC, Aki-7 commented on zen/pointer.c
> +  struct zn_pointer* self;
I want this declaration to be placed at the beginning of the scope. I missed the same code in keyboard.c, please fix it as well.

2022-08-06 04:45 UTC, Aki-7 approved these changes
LGTM!

2022-08-06 04:46 UTC, merged