Change the timing of creating and starting xwayland with lazy option
zigen-project/zen pull request #99
Opened 2022-08-04 09:43 UTC by shierote

## Context

fix https://github.com/zigen-project/zen/issues/82.

## Summary

- To use x client in startup command (or `-s` option), xwayland is started with lazy option in `zn_server_create` instead of `zn_server_run`.
- Some corrections, including mistakes that destructor is not written.

## How to check behavior

```
$ zen-desktop -s xeyes
```
Then, the monitor shows xeyes's window.

Without this pr, this command terminates zen-desktop without showing any windows.

2022-08-04 14:24 UTC, liwii requested changes

2022-08-04 14:24 UTC, liwii commented on zen/server.c
> +  self->xwayland = wlr_xwayland_create(self->display, self->w_compositor, true);
Could we move L241 ~ 248 before the `zn_input_manager_create`? It seems a bit weird that input-related code is divided by this xwayland block.

2022-08-05 11:29 UTC, shierote commented on zen/server.c
> +  self->xwayland = wlr_xwayland_create(self->display, self->w_compositor, true);
Thanks for your review!
Do you recognize `zn_input_manager_create`  and `self->new_input_listener.notify = zn_server_new_input_handler;..` as input-related code? (confirmation)

I intended that xwayland would be optional in the future, so I am writing it at the bottom of the member creation step.
However, this intention is not a strong one, so if you feel that it is wired after hearing this intention, then I will fix it as you said.

2022-08-05 13:07 UTC, Aki-7 commented on zen/server.c
> +  self->xwayland = wlr_xwayland_create(self->display, self->w_compositor, true);
That doesn't seem weird for me. Rather than the xwayland block being placed between the input manager-related code, it seems more natural to think that it was placed at the end of the member creation block and before the register event listener block.

2022-08-05 13:08 UTC, Aki-7 approved these changes

2022-08-05 13:08 UTC, Aki-7 commented on zen/server.c
> +  zn_immersive_backend_destroy(self->immersive_backend);
thx

2022-08-05 13:31 UTC, watasuke102 commented on zen/server.c
> +  self->xwayland = wlr_xwayland_create(self->display, self->w_compositor, true);
Hmm, it is actually true that that block is placed between member creation block and before the register event listener block. But if divide member creation block more, I think it is also true that input-related code is divided by xwayland block.

Pointed out lines seem to relate xwayland, so unless there is no reason to put these above creating input-related code, it seems moving this process is good.

2022-08-05 13:36 UTC, Aki-7 commented on zen/server.c
> +  self->xwayland = wlr_xwayland_create(self->display, self->w_compositor, true);
Rather xwayland block beeing between member creation block and event registration block, it seems one of the member creation block for me. If someone want to add another member creation block that is related to input manager, it's ok to place the block between xwayland block and input manager block.

2022-08-15 03:18 UTC, merged